create table poochku.enquiry (enquiry_id bigserial not null, type varchar(255), pet_id bigint, user_id bigint, primary key (enquiry_id));
create table poochku.pet (pet_id bigserial not null, age integer, breed varchar(255), crt_ts date, description varchar(255), father_breed varchar(255), gender varchar(255), location varchar(255), mother_breed varchar(255), name varchar(255), status varchar(255), pet_type varchar(255), quality varchar(255), vaccination_status boolean, seller_id bigint, user_id bigint, primary key (pet_id));
create table poochku.pet_images (pet_image_id bigserial not null, url varchar(255) array, pet_id bigint, primary key (pet_image_id));
create table poochku.pet_service (pet_service_id bigserial not null, price integer, service_code varchar(255), service_name varchar(255), pet_id bigint, primary key (pet_service_id));
create table poochku.seller (seller_id bigserial not null, crt_ts timestamp(6), email varchar(255), f_name varchar(255), l_name varchar(255), last_login timestamp(6), m_name varchar(255), password varchar(255), phone_no varchar(255), user_role varchar(255) array, primary key (seller_id));
create table poochku.subscription_plan (plan_id bigserial not null, description varchar(255), duration_in_days integer not null, name varchar(255) not null, price float(53) not null, primary key (plan_id));
create table poochku.swipe (swipe_id bigserial not null, created_at timestamp(6), direction varchar(255), status varchar(255), swiper_id bigint, target_id bigint, primary key (swipe_id));
create table poochku.user (user_id bigserial not null, crt_ts timestamp(6), email varchar(255), f_name varchar(255), l_name varchar(255), last_login timestamp(6), m_name varchar(255), password varchar(255), phone_no varchar(255), user_role varchar(255), primary key (user_id));
create table user_subscription (subscription_id bigserial not null, crt_ts date not null, payment_date date not null, payment_info varchar(255), payment_status varchar(255) not null, subscription_expiry_date date not null, subscription_status varchar(255) not null, subscription_tier varchar(255), plan_id bigint not null, seller_id bigint not null, primary key (subscription_id));
alter table if exists poochku.enquiry add constraint FK5c9mglj362p3vn6ekvjajds2q foreign key (pet_id) references poochku.pet;
alter table if exists poochku.enquiry add constraint FK613vt3u3d7f0banlvwmk65mnk foreign key (user_id) references poochku.seller;
alter table if exists poochku.pet add constraint FKb7i04g9ccv3p6nllnijodhkth foreign key (seller_id) references poochku.seller;
alter table if exists poochku.pet add constraint FK9hxka0oqkd15dmqstdarori08 foreign key (user_id) references poochku.user;
alter table if exists poochku.pet_images add constraint FKjv5ge6puunoipe1pkod8dlmwq foreign key (pet_id) references poochku.pet;
alter table if exists poochku.pet_service add constraint FK62niqikbhm9jxhjvd2uke5obm foreign key (pet_id) references poochku.pet;
alter table if exists poochku.swipe add constraint FKmec80mqhxf8ceo1f75wgpug8 foreign key (swiper_id) references poochku.pet;
alter table if exists poochku.swipe add constraint FKj6vero838d2j395b78grx0r7k foreign key (target_id) references poochku.pet;
alter table if exists poochku.user_subscription add constraint FK5jwayho30sj0jbg6llcsqe88h foreign key (plan_id) references poochku.subscription_plan;
alter table if exists poochku.user_subscription add constraint FK3ioo9vtg9x2oifhjh4801lfio foreign key (seller_id) references poochku.seller;
create table poochku.enquiry (enquiry_id bigserial not null, type varchar(255), pet_id bigint, user_id bigint, primary key (enquiry_id));
create table poochku.pet (pet_id bigserial not null, age integer, breed varchar(255), crt_ts date, description varchar(255), father_breed varchar(255), gender varchar(255), location varchar(255), mother_breed varchar(255), name varchar(255), status varchar(255), pet_type varchar(255), quality varchar(255), vaccination_status boolean, seller_id bigint, user_id bigint, primary key (pet_id));
create table poochku.pet_images (pet_image_id bigserial not null, url varchar(255) array, pet_id bigint, primary key (pet_image_id));
create table poochku.pet_service (pet_service_id bigserial not null, price integer, service_code varchar(255), service_name varchar(255), pet_id bigint, primary key (pet_service_id));
create table poochku.seller (seller_id bigserial not null, crt_ts timestamp(6), email varchar(255), f_name varchar(255), l_name varchar(255), last_login timestamp(6), m_name varchar(255), password varchar(255), phone_no varchar(255), user_role varchar(255) array, primary key (seller_id));
create table poochku.subscription_plan (plan_id bigserial not null, description varchar(255), duration_in_days integer not null, name varchar(255) not null, price float(53) not null, primary key (plan_id));
create table poochku.swipe (swipe_id bigserial not null, created_at timestamp(6), direction varchar(255), status varchar(255), swiper_id bigint, target_id bigint, primary key (swipe_id));
create table poochku.user (user_id bigserial not null, crt_ts timestamp(6), email varchar(255), f_name varchar(255), l_name varchar(255), last_login timestamp(6), m_name varchar(255), password varchar(255), phone_no varchar(255), user_role varchar(255), primary key (user_id));
create table poochku.user_subscription (subscription_id bigserial not null, crt_ts date not null, payment_date date not null, payment_info varchar(255), payment_status varchar(255) not null, subscription_expiry_date date not null, subscription_status varchar(255) not null, subscription_tier varchar(255), plan_id bigint not null, seller_id bigint not null, primary key (subscription_id));
alter table if exists poochku.enquiry add constraint FK5c9mglj362p3vn6ekvjajds2q foreign key (pet_id) references poochku.pet;
alter table if exists poochku.enquiry add constraint FK613vt3u3d7f0banlvwmk65mnk foreign key (user_id) references poochku.seller;
alter table if exists poochku.pet add constraint FKb7i04g9ccv3p6nllnijodhkth foreign key (seller_id) references poochku.seller;
alter table if exists poochku.pet add constraint FK9hxka0oqkd15dmqstdarori08 foreign key (user_id) references poochku.user;
alter table if exists poochku.pet_images add constraint FKjv5ge6puunoipe1pkod8dlmwq foreign key (pet_id) references poochku.pet;
alter table if exists poochku.pet_service add constraint FK62niqikbhm9jxhjvd2uke5obm foreign key (pet_id) references poochku.pet;
alter table if exists poochku.swipe add constraint FKmec80mqhxf8ceo1f75wgpug8 foreign key (swiper_id) references poochku.pet;
alter table if exists poochku.swipe add constraint FKj6vero838d2j395b78grx0r7k foreign key (target_id) references poochku.pet;
alter table if exists poochku.user_subscription add constraint FK5jwayho30sj0jbg6llcsqe88h foreign key (plan_id) references poochku.subscription_plan;
alter table if exists poochku.user_subscription add constraint FK3ioo9vtg9x2oifhjh4801lfio foreign key (seller_id) references poochku.seller;
create table poochku.enquiry (enquiry_id bigserial not null, type varchar(255), pet_id bigint, user_id bigint, primary key (enquiry_id));
create table poochku.pet (pet_id bigserial not null, age integer, breed varchar(255), crt_ts date, description varchar(255), father_breed varchar(255), gender varchar(255), location varchar(255), mother_breed varchar(255), name varchar(255), status varchar(255), pet_type varchar(255), quality varchar(255), vaccination_status boolean, seller_id bigint, user_id bigint, primary key (pet_id));
create table poochku.pet_images (pet_image_id bigserial not null, url varchar(255) array, pet_id bigint, primary key (pet_image_id));
create table poochku.pet_service (pet_service_id bigserial not null, price integer, service_code varchar(255), service_name varchar(255), pet_id bigint, primary key (pet_service_id));
create table poochku.seller (seller_id bigserial not null, crt_ts timestamp(6), email varchar(255), f_name varchar(255), l_name varchar(255), last_login timestamp(6), m_name varchar(255), password varchar(255), phone_no varchar(255), user_role varchar(255) array, primary key (seller_id));
create table poochku.subscription_plan (plan_id bigserial not null, description varchar(255), duration_in_days integer not null, name varchar(255) not null, price float(53) not null, primary key (plan_id));
create table poochku.swipe (swipe_id bigserial not null, created_at timestamp(6), direction varchar(255), status varchar(255), swiper_id bigint, target_id bigint, primary key (swipe_id));
create table poochku.user (user_id bigserial not null, crt_ts timestamp(6), email varchar(255), f_name varchar(255), l_name varchar(255), last_login timestamp(6), m_name varchar(255), password varchar(255), phone_no varchar(255), user_role varchar(255), primary key (user_id));
create table poochku.user_subscription (subscription_id bigserial not null, crt_ts date not null, payment_date date not null, payment_info varchar(255), payment_status varchar(255) not null, subscription_expiry_date date not null, subscription_status varchar(255) not null, subscription_tier varchar(255), plan_id bigint not null, seller_id bigint not null, primary key (subscription_id));
alter table if exists poochku.enquiry add constraint FK5c9mglj362p3vn6ekvjajds2q foreign key (pet_id) references poochku.pet;
alter table if exists poochku.enquiry add constraint FK613vt3u3d7f0banlvwmk65mnk foreign key (user_id) references poochku.seller;
alter table if exists poochku.pet add constraint FKb7i04g9ccv3p6nllnijodhkth foreign key (seller_id) references poochku.seller;
alter table if exists poochku.pet add constraint FK9hxka0oqkd15dmqstdarori08 foreign key (user_id) references poochku.user;
alter table if exists poochku.pet_images add constraint FKjv5ge6puunoipe1pkod8dlmwq foreign key (pet_id) references poochku.pet;
alter table if exists poochku.pet_service add constraint FK62niqikbhm9jxhjvd2uke5obm foreign key (pet_id) references poochku.pet;
alter table if exists poochku.swipe add constraint FKmec80mqhxf8ceo1f75wgpug8 foreign key (swiper_id) references poochku.pet;
alter table if exists poochku.swipe add constraint FKj6vero838d2j395b78grx0r7k foreign key (target_id) references poochku.pet;
alter table if exists poochku.user_subscription add constraint FK5jwayho30sj0jbg6llcsqe88h foreign key (plan_id) references poochku.subscription_plan;
alter table if exists poochku.user_subscription add constraint FK3ioo9vtg9x2oifhjh4801lfio foreign key (seller_id) references poochku.seller;
