openapi: 3.0.3
info:
  title: Poochku API
  version: 1.0.0
  description: Poochku API documentation
servers:
  - url: http://localhost:8080/api/v1
paths:
  /auth/login:
    post:
      summary: Authenticate a User
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestDto'
      responses:
        '200':
          description: User Authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginSuccessResponseDto'
        '403':
          description: Token not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: Username not Valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

  /users:
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{userId}:
    get:
      summary: Retrieve a user by ID
      operationId: requestUserInfo
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User Details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
        '400':
          description: Bad Request. Missing required parameters
components:
  schemas:
    User:
      type: object
      properties:
        userId:
          type: integer
        fName:
          type: string
        lName:
          type: string
        email:
          type: string
        password:
          type: string
        phoneNo:
          type: string
        petList:
          type: array
          items:
            $ref: '#/components/schemas/Pet'

    Pet:
      type: object
      properties:
        petId:
          type: integer
        name:
          type: string
        petType:
          type: string
        breed:
          type: string
        description:
          type: string
        service:
          $ref: '#/components/schemas/Service'

    Service:
      type: object
      properties:
        serviceId:
          type: integer
        serviceName:
          type: string
        serviceCode:
          type: string

    LoginRequestDto:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

    LoginSuccessResponseDto:
      type: object
      properties:
        token:
          type: string

    ErrorResponseDto:
      type: object
      properties:
        statusCode:
          type: integer
        message:
          type: string
        timestamp:
          type: string
        uuid:
          type: string
